# This is a basic workflow to help you get started with Actions

name: sync

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch

on:
  schedule:
    - cron: '30 */12 * * *'

  workflow_dispatch:
  
  watch:
    types: started   
    
  repository_dispatch:
    types: sync
    
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync lxk0301
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "lxk0301_jd_scripts"
          github_token: ${{ secrets.PAT }}
          
      - name: sync sazs34-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/sazs34/MyActions.git"
          source_branch: "master"
          destination_branch: "sazs34_Myactions"
          github_token: ${{ secrets.PAT }}
          
      - name: DivineEngine-Profiles
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/DivineEngine/Profiles.git"
          source_branch: "master"
          destination_branch: "DivineEngine-Profiles"
          github_token: ${{ secrets.PAT }}
          
      - name: GeQ1an-Rules
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/GeQ1an/Rules.git"
          source_branch: "master"
          destination_branch: "GeQ1an-Rules"
          github_token: ${{ secrets.PAT }}
          
      - name: KOP-XIAO-QuantumultX-Surge-API
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/KOP-XIAO/QuantumultX-Surge-API.git"
          source_branch: "master"
          destination_branch: "KOP-XIAO-QuantumultX-Surge-API"
          github_token: ${{ secrets.PAT }}
          
      - name: KOP-XIAO-QuantumultX
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/KOP-XIAO/QuantumultX.git"
          source_branch: "master"
          destination_branch: "KOP-XIAO-QuantumultX"
          github_token: ${{ secrets.PAT }}
          
      - name: NobyDa-Script
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/NobyDa/Script.git"
          source_branch: "master"
          destination_branch: "NobyDa-Script"
          github_token: ${{ secrets.PAT }}
          
      - name: Orz-3-QuantumultX
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Orz-3/QuantumultX.git"
          source_branch: "master"
          destination_branch: "Orz-3-QuantumultX"
          github_token: ${{ secrets.PAT }}
          
      - name: blackmatrix7-ios_rule_script
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/blackmatrix7/ios_rule_script.git"
          source_branch: "master"
          destination_branch: "blackmatrix7-ios_rule_script"
          github_token: ${{ secrets.PAT }}
          
      - name: chavyleung-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/chavyleung/scripts.git"
          source_branch: "master"
          destination_branch: "chavyleung-scripts"
          github_token: ${{ secrets.PAT }}
          
      - name: lhie1-Rules
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lhie1/Rules.git"
          source_branch: "master"
          destination_branch: "lhie1-Rules"
          github_token: ${{ secrets.PAT }}

          
      - name: yichahucha-surge
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/yichahucha/surge.git"
          source_branch: "master"
          destination_branch: "yichahucha-surge"
          github_token: ${{ secrets.PAT }}
          

